/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Category {
  'id' : string,
  'status' : Status__1,
  'name' : string,
  'description' : [] | [string],
}
export type ExternalBlob = Uint8Array;
export interface Inquiry {
  'id' : string,
  'status' : InquiryStatus,
  'response_text' : [] | [string],
  'created_at' : bigint,
  'worker_id' : string,
  'customer_contact' : [] | [string],
  'response_given' : boolean,
  'customer_name' : [] | [string],
  'inquiry_text' : string,
  'inquiry_type' : InquiryType,
}
export type InquiryStatus = { 'new' : null } |
  { 'pending' : null } |
  { 'completed' : null };
export type InquiryType = { 'question' : null } |
  { 'feedback' : null } |
  { 'booking' : null };
export interface Integrations {
  'website_url' : [] | [string],
  'instagram_handle' : [] | [string],
  'whatsapp_number' : [] | [string],
  'facebook_username' : [] | [string],
}
export interface Location {
  'latitude' : [] | [number],
  'country' : [] | [string],
  'city' : [] | [string],
  'district' : [] | [string],
  'longitude' : [] | [number],
  'address' : [] | [string],
}
export interface Pricing {
  'rate_per_day' : [] | [bigint],
  'special_offers' : Array<string>,
  'rate_per_hour' : [] | [bigint],
  'currency' : [] | [string],
}
export interface Schedule {
  'timezone' : [] | [string],
  'close_time' : [] | [string],
  'available_days' : Array<string>,
  'open_time' : [] | [string],
}
export type Status = { 'featured' : null } |
  { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type Status__1 = { 'active' : null } |
  { 'pending_approval' : null } |
  { 'rejected' : null } |
  { 'suspended' : null };
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkerProfile {
  'id' : string,
  'status' : Status,
  'principal' : Principal,
  'integrations' : Integrations,
  'published' : boolean,
  'pricing' : Pricing,
  'availability' : Schedule,
  'years_experience' : bigint,
  'photo' : [] | [ExternalBlob],
  'phone_number' : string,
  'location' : Location,
  'full_name' : string,
  'category_id' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveWorker' : ActorMethod<
    [[] | [string], [] | [string], string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCategory' : ActorMethod<
    [[] | [string], [] | [string], Category],
    undefined
  >,
  'createInquiry' : ActorMethod<[Inquiry], undefined>,
  'deleteCategory' : ActorMethod<
    [[] | [string], [] | [string], string],
    undefined
  >,
  'deleteInquiry' : ActorMethod<
    [[] | [string], [] | [string], string],
    undefined
  >,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getAllInquiries' : ActorMethod<
    [[] | [string], [] | [string]],
    Array<Inquiry>
  >,
  'getAllWorkers' : ActorMethod<[], Array<WorkerProfile>>,
  'getAllWorkersAdmin' : ActorMethod<
    [[] | [string], [] | [string]],
    Array<WorkerProfile>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategory' : ActorMethod<[string], [] | [Category]>,
  'getMyWorkerProfile' : ActorMethod<[], [] | [WorkerProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkerInquiries' : ActorMethod<[string], Array<Inquiry>>,
  'getWorkerInquiriesAdmin' : ActorMethod<
    [[] | [string], [] | [string], string],
    Array<Inquiry>
  >,
  'getWorkerProfile' : ActorMethod<[string], [] | [WorkerProfile]>,
  'getWorkerProfileAdmin' : ActorMethod<
    [[] | [string], [] | [string], string],
    [] | [WorkerProfile]
  >,
  'getWorkersByCategory' : ActorMethod<[string], Array<WorkerProfile>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'publishWorker' : ActorMethod<
    [[] | [string], [] | [string], string],
    undefined
  >,
  'registerWorker' : ActorMethod<[WorkerProfile], undefined>,
  'rejectWorker' : ActorMethod<
    [[] | [string], [] | [string], string],
    undefined
  >,
  'removeWorker' : ActorMethod<
    [[] | [string], [] | [string], string],
    undefined
  >,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'unpublishWorker' : ActorMethod<
    [[] | [string], [] | [string], string],
    undefined
  >,
  'updateCategory' : ActorMethod<
    [[] | [string], [] | [string], string, Category],
    undefined
  >,
  'updateInquiry' : ActorMethod<
    [[] | [string], [] | [string], string, Inquiry],
    undefined
  >,
  'updateWorkerProfile' : ActorMethod<[string, WorkerProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];