/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Status__1 = IDL.Variant({
  'active' : IDL.Null,
  'pending_approval' : IDL.Null,
  'rejected' : IDL.Null,
  'suspended' : IDL.Null,
});
export const Category = IDL.Record({
  'id' : IDL.Text,
  'status' : Status__1,
  'name' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
});
export const InquiryStatus = IDL.Variant({
  'new' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const InquiryType = IDL.Variant({
  'question' : IDL.Null,
  'feedback' : IDL.Null,
  'booking' : IDL.Null,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Text,
  'status' : InquiryStatus,
  'response_text' : IDL.Opt(IDL.Text),
  'created_at' : IDL.Int,
  'worker_id' : IDL.Text,
  'customer_contact' : IDL.Opt(IDL.Text),
  'response_given' : IDL.Bool,
  'customer_name' : IDL.Opt(IDL.Text),
  'inquiry_text' : IDL.Text,
  'inquiry_type' : InquiryType,
});
export const Status = IDL.Variant({
  'featured' : IDL.Null,
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Integrations = IDL.Record({
  'website_url' : IDL.Opt(IDL.Text),
  'instagram_handle' : IDL.Opt(IDL.Text),
  'whatsapp_number' : IDL.Opt(IDL.Text),
  'facebook_username' : IDL.Opt(IDL.Text),
});
export const Pricing = IDL.Record({
  'rate_per_day' : IDL.Opt(IDL.Nat),
  'special_offers' : IDL.Vec(IDL.Text),
  'rate_per_hour' : IDL.Opt(IDL.Nat),
  'currency' : IDL.Opt(IDL.Text),
});
export const Schedule = IDL.Record({
  'timezone' : IDL.Opt(IDL.Text),
  'close_time' : IDL.Opt(IDL.Text),
  'available_days' : IDL.Vec(IDL.Text),
  'open_time' : IDL.Opt(IDL.Text),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Location = IDL.Record({
  'latitude' : IDL.Opt(IDL.Float64),
  'country' : IDL.Opt(IDL.Text),
  'city' : IDL.Opt(IDL.Text),
  'district' : IDL.Opt(IDL.Text),
  'longitude' : IDL.Opt(IDL.Float64),
  'address' : IDL.Opt(IDL.Text),
});
export const WorkerProfile = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'principal' : IDL.Principal,
  'integrations' : Integrations,
  'published' : IDL.Bool,
  'pricing' : Pricing,
  'availability' : Schedule,
  'years_experience' : IDL.Nat,
  'photo' : IDL.Opt(ExternalBlob),
  'phone_number' : IDL.Text,
  'location' : Location,
  'full_name' : IDL.Text,
  'category_id' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveWorker' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), Category],
      [],
      [],
    ),
  'createInquiry' : IDL.Func([Inquiry], [], []),
  'deleteCategory' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'deleteInquiry' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getAllInquiries' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(Inquiry)],
      [],
    ),
  'getAllWorkers' : IDL.Func([], [IDL.Vec(WorkerProfile)], ['query']),
  'getAllWorkersAdmin' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(WorkerProfile)],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategory' : IDL.Func([IDL.Text], [IDL.Opt(Category)], ['query']),
  'getMyWorkerProfile' : IDL.Func([], [IDL.Opt(WorkerProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkerInquiries' : IDL.Func([IDL.Text], [IDL.Vec(Inquiry)], ['query']),
  'getWorkerInquiriesAdmin' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
      [IDL.Vec(Inquiry)],
      [],
    ),
  'getWorkerProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(WorkerProfile)],
      ['query'],
    ),
  'getWorkerProfileAdmin' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
      [IDL.Opt(WorkerProfile)],
      [],
    ),
  'getWorkersByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WorkerProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'publishWorker' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'registerWorker' : IDL.Func([WorkerProfile], [], []),
  'rejectWorker' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'removeWorker' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'unpublishWorker' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'updateCategory' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text, Category],
      [],
      [],
    ),
  'updateInquiry' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text, Inquiry],
      [],
      [],
    ),
  'updateWorkerProfile' : IDL.Func([IDL.Text, WorkerProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Status__1 = IDL.Variant({
    'active' : IDL.Null,
    'pending_approval' : IDL.Null,
    'rejected' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const Category = IDL.Record({
    'id' : IDL.Text,
    'status' : Status__1,
    'name' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
  });
  const InquiryStatus = IDL.Variant({
    'new' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const InquiryType = IDL.Variant({
    'question' : IDL.Null,
    'feedback' : IDL.Null,
    'booking' : IDL.Null,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Text,
    'status' : InquiryStatus,
    'response_text' : IDL.Opt(IDL.Text),
    'created_at' : IDL.Int,
    'worker_id' : IDL.Text,
    'customer_contact' : IDL.Opt(IDL.Text),
    'response_given' : IDL.Bool,
    'customer_name' : IDL.Opt(IDL.Text),
    'inquiry_text' : IDL.Text,
    'inquiry_type' : InquiryType,
  });
  const Status = IDL.Variant({
    'featured' : IDL.Null,
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Integrations = IDL.Record({
    'website_url' : IDL.Opt(IDL.Text),
    'instagram_handle' : IDL.Opt(IDL.Text),
    'whatsapp_number' : IDL.Opt(IDL.Text),
    'facebook_username' : IDL.Opt(IDL.Text),
  });
  const Pricing = IDL.Record({
    'rate_per_day' : IDL.Opt(IDL.Nat),
    'special_offers' : IDL.Vec(IDL.Text),
    'rate_per_hour' : IDL.Opt(IDL.Nat),
    'currency' : IDL.Opt(IDL.Text),
  });
  const Schedule = IDL.Record({
    'timezone' : IDL.Opt(IDL.Text),
    'close_time' : IDL.Opt(IDL.Text),
    'available_days' : IDL.Vec(IDL.Text),
    'open_time' : IDL.Opt(IDL.Text),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Location = IDL.Record({
    'latitude' : IDL.Opt(IDL.Float64),
    'country' : IDL.Opt(IDL.Text),
    'city' : IDL.Opt(IDL.Text),
    'district' : IDL.Opt(IDL.Text),
    'longitude' : IDL.Opt(IDL.Float64),
    'address' : IDL.Opt(IDL.Text),
  });
  const WorkerProfile = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'principal' : IDL.Principal,
    'integrations' : Integrations,
    'published' : IDL.Bool,
    'pricing' : Pricing,
    'availability' : Schedule,
    'years_experience' : IDL.Nat,
    'photo' : IDL.Opt(ExternalBlob),
    'phone_number' : IDL.Text,
    'location' : Location,
    'full_name' : IDL.Text,
    'category_id' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveWorker' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), Category],
        [],
        [],
      ),
    'createInquiry' : IDL.Func([Inquiry], [], []),
    'deleteCategory' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'deleteInquiry' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getAllInquiries' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(Inquiry)],
        [],
      ),
    'getAllWorkers' : IDL.Func([], [IDL.Vec(WorkerProfile)], ['query']),
    'getAllWorkersAdmin' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(WorkerProfile)],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategory' : IDL.Func([IDL.Text], [IDL.Opt(Category)], ['query']),
    'getMyWorkerProfile' : IDL.Func([], [IDL.Opt(WorkerProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkerInquiries' : IDL.Func([IDL.Text], [IDL.Vec(Inquiry)], ['query']),
    'getWorkerInquiriesAdmin' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
        [IDL.Vec(Inquiry)],
        [],
      ),
    'getWorkerProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(WorkerProfile)],
        ['query'],
      ),
    'getWorkerProfileAdmin' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
        [IDL.Opt(WorkerProfile)],
        [],
      ),
    'getWorkersByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WorkerProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'publishWorker' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'registerWorker' : IDL.Func([WorkerProfile], [], []),
    'rejectWorker' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'removeWorker' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'unpublishWorker' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'updateCategory' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text, Category],
        [],
        [],
      ),
    'updateInquiry' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text, Inquiry],
        [],
        [],
      ),
    'updateWorkerProfile' : IDL.Func([IDL.Text, WorkerProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };