/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    latitude?: number;
    country?: string;
    city?: string;
    district?: string;
    longitude?: number;
    address?: string;
}
export interface Category {
    id: string;
    status: Status__1;
    name: string;
    description?: string;
}
export interface Pricing {
    rate_per_day?: bigint;
    special_offers: Array<string>;
    rate_per_hour?: bigint;
    currency?: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Schedule {
    timezone?: string;
    close_time?: string;
    available_days: Array<string>;
    open_time?: string;
}
export interface Integrations {
    website_url?: string;
    instagram_handle?: string;
    whatsapp_number?: string;
    facebook_username?: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface WorkerProfile {
    id: string;
    status: Status;
    principal: Principal;
    integrations: Integrations;
    pricing: Pricing;
    availability: Schedule;
    years_experience: bigint;
    photo?: ExternalBlob;
    phone_number: string;
    location: Location;
    full_name: string;
    category_id: string;
}
export interface Inquiry {
    id: string;
    status: InquiryStatus;
    response_text?: string;
    created_at: bigint;
    worker_id: string;
    customer_contact?: string;
    response_given: boolean;
    customer_name?: string;
    inquiry_text: string;
    inquiry_type: InquiryType;
}
export interface UserProfile {
    name: string;
    role: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum InquiryStatus {
    new_ = "new",
    pending = "pending",
    completed = "completed"
}
export enum InquiryType {
    question = "question",
    feedback = "feedback",
    booking = "booking"
}
export enum Status {
    featured = "featured",
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum Status__1 {
    active = "active",
    pending_approval = "pending_approval",
    rejected = "rejected",
    suspended = "suspended"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveWorker(username: string | null, password: string | null, workerId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCategory(username: string | null, password: string | null, category: Category): Promise<void>;
    createInquiry(inquiry: Inquiry): Promise<void>;
    deleteCategory(username: string | null, password: string | null, categoryId: string): Promise<void>;
    deleteInquiry(username: string | null, password: string | null, inquiryId: string): Promise<void>;
    getAllCategories(): Promise<Array<Category>>;
    getAllInquiries(username: string | null, password: string | null): Promise<Array<Inquiry>>;
    getAllWorkers(): Promise<Array<WorkerProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCategory(categoryId: string): Promise<Category | null>;
    getMyWorkerProfile(): Promise<WorkerProfile | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWorkerInquiries(workerId: string): Promise<Array<Inquiry>>;
    getWorkerProfile(workerId: string): Promise<WorkerProfile | null>;
    getWorkersByCategory(categoryId: string): Promise<Array<WorkerProfile>>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    registerWorker(profile: WorkerProfile): Promise<void>;
    rejectWorker(username: string | null, password: string | null, workerId: string): Promise<void>;
    removeWorker(username: string | null, password: string | null, workerId: string): Promise<void>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    updateCategory(username: string | null, password: string | null, categoryId: string, category: Category): Promise<void>;
    updateInquiry(username: string | null, password: string | null, inquiryId: string, inquiry: Inquiry): Promise<void>;
    updateWorkerProfile(workerId: string, profile: WorkerProfile): Promise<void>;
}
import type { ApprovalStatus as _ApprovalStatus, Category as _Category, ExternalBlob as _ExternalBlob, Inquiry as _Inquiry, InquiryStatus as _InquiryStatus, InquiryType as _InquiryType, Integrations as _Integrations, Location as _Location, Pricing as _Pricing, Schedule as _Schedule, Status as _Status, Status__1 as _Status__1, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, WorkerProfile as _WorkerProfile, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveWorker(arg0: string | null, arg1: string | null, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveWorker(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveWorker(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCategory(arg0: string | null, arg1: string | null, arg2: Category): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCategory(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), to_candid_Category_n11(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCategory(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), to_candid_Category_n11(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createInquiry(arg0: Inquiry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createInquiry(to_candid_Inquiry_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInquiry(to_candid_Inquiry_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteCategory(arg0: string | null, arg1: string | null, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async deleteInquiry(arg0: string | null, arg1: string | null, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInquiry(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInquiry(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async getAllCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCategories();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCategories();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInquiries(arg0: string | null, arg1: string | null): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInquiries(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInquiries(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWorkers(): Promise<Array<WorkerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWorkers();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWorkers();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategory(arg0: string): Promise<Category | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategory(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategory(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWorkerProfile(): Promise<WorkerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWorkerProfile();
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWorkerProfile();
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkerInquiries(arg0: string): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkerInquiries(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkerInquiries(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkerProfile(arg0: string): Promise<WorkerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkerProfile(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkerProfile(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkersByCategory(arg0: string): Promise<Array<WorkerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkersByCategory(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkersByCategory(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerWorker(arg0: WorkerProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerWorker(await to_candid_WorkerProfile_n60(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerWorker(await to_candid_WorkerProfile_n60(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async rejectWorker(arg0: string | null, arg1: string | null, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectWorker(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectWorker(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async removeWorker(arg0: string | null, arg1: string | null, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeWorker(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeWorker(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n73(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n73(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateCategory(arg0: string | null, arg1: string | null, arg2: string, arg3: Category): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_Category_n11(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_Category_n11(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateInquiry(arg0: string | null, arg1: string | null, arg2: string, arg3: Inquiry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInquiry(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_Inquiry_n15(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInquiry(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_Inquiry_n15(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateWorkerProfile(arg0: string, arg1: WorkerProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkerProfile(arg0, await to_candid_WorkerProfile_n60(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkerProfile(arg0, await to_candid_WorkerProfile_n60(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_InquiryStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InquiryStatus): InquiryStatus {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_InquiryType_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InquiryType): InquiryType {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Inquiry_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Inquiry): Inquiry {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Integrations_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Integrations): Integrations {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Location_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Location): Location {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_Pricing_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Pricing): Pricing {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Schedule_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Schedule): Schedule {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Status__1_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status__1): Status__1 {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
async function from_candid_WorkerProfile_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkerProfile): Promise<WorkerProfile> {
    return await from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n46(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Category]): Category | null {
    return value.length === 0 ? null : from_candid_Category_n22(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WorkerProfile]): Promise<WorkerProfile | null> {
    return value.length === 0 ? null : await from_candid_WorkerProfile_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _Status__1;
    name: string;
    description: [] | [string];
}): {
    id: string;
    status: Status__1;
    name: string;
    description?: string;
} {
    return {
        id: value.id,
        status: from_candid_Status__1_n24(_uploadFile, _downloadFile, value.status),
        name: value.name,
        description: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.description))
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _InquiryStatus;
    response_text: [] | [string];
    created_at: bigint;
    worker_id: string;
    customer_contact: [] | [string];
    response_given: boolean;
    customer_name: [] | [string];
    inquiry_text: string;
    inquiry_type: _InquiryType;
}): {
    id: string;
    status: InquiryStatus;
    response_text?: string;
    created_at: bigint;
    worker_id: string;
    customer_contact?: string;
    response_given: boolean;
    customer_name?: string;
    inquiry_text: string;
    inquiry_type: InquiryType;
} {
    return {
        id: value.id,
        status: from_candid_InquiryStatus_n30(_uploadFile, _downloadFile, value.status),
        response_text: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.response_text)),
        created_at: value.created_at,
        worker_id: value.worker_id,
        customer_contact: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.customer_contact)),
        response_given: value.response_given,
        customer_name: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.customer_name)),
        inquiry_text: value.inquiry_text,
        inquiry_type: from_candid_InquiryType_n32(_uploadFile, _downloadFile, value.inquiry_type)
    };
}
async function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _Status;
    principal: Principal;
    integrations: _Integrations;
    pricing: _Pricing;
    availability: _Schedule;
    years_experience: bigint;
    photo: [] | [_ExternalBlob];
    phone_number: string;
    location: _Location;
    full_name: string;
    category_id: string;
}): Promise<{
    id: string;
    status: Status;
    principal: Principal;
    integrations: Integrations;
    pricing: Pricing;
    availability: Schedule;
    years_experience: bigint;
    photo?: ExternalBlob;
    phone_number: string;
    location: Location;
    full_name: string;
    category_id: string;
}> {
    return {
        id: value.id,
        status: from_candid_Status_n37(_uploadFile, _downloadFile, value.status),
        principal: value.principal,
        integrations: from_candid_Integrations_n39(_uploadFile, _downloadFile, value.integrations),
        pricing: from_candid_Pricing_n41(_uploadFile, _downloadFile, value.pricing),
        availability: from_candid_Schedule_n43(_uploadFile, _downloadFile, value.availability),
        years_experience: value.years_experience,
        photo: record_opt_to_undefined(await from_candid_opt_n45(_uploadFile, _downloadFile, value.photo)),
        phone_number: value.phone_number,
        location: from_candid_Location_n47(_uploadFile, _downloadFile, value.location),
        full_name: value.full_name,
        category_id: value.category_id
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    website_url: [] | [string];
    instagram_handle: [] | [string];
    whatsapp_number: [] | [string];
    facebook_username: [] | [string];
}): {
    website_url?: string;
    instagram_handle?: string;
    whatsapp_number?: string;
    facebook_username?: string;
} {
    return {
        website_url: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.website_url)),
        instagram_handle: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.instagram_handle)),
        whatsapp_number: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.whatsapp_number)),
        facebook_username: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.facebook_username))
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rate_per_day: [] | [bigint];
    special_offers: Array<string>;
    rate_per_hour: [] | [bigint];
    currency: [] | [string];
}): {
    rate_per_day?: bigint;
    special_offers: Array<string>;
    rate_per_hour?: bigint;
    currency?: string;
} {
    return {
        rate_per_day: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.rate_per_day)),
        special_offers: value.special_offers,
        rate_per_hour: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.rate_per_hour)),
        currency: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.currency))
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    timezone: [] | [string];
    close_time: [] | [string];
    available_days: Array<string>;
    open_time: [] | [string];
}): {
    timezone?: string;
    close_time?: string;
    available_days: Array<string>;
    open_time?: string;
} {
    return {
        timezone: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.timezone)),
        close_time: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.close_time)),
        available_days: value.available_days,
        open_time: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.open_time))
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude: [] | [number];
    country: [] | [string];
    city: [] | [string];
    district: [] | [string];
    longitude: [] | [number];
    address: [] | [string];
}): {
    latitude?: number;
    country?: string;
    city?: string;
    district?: string;
    longitude?: number;
    address?: string;
} {
    return {
        latitude: record_opt_to_undefined(from_candid_opt_n49(_uploadFile, _downloadFile, value.latitude)),
        country: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.country)),
        city: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.city)),
        district: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.district)),
        longitude: record_opt_to_undefined(from_candid_opt_n49(_uploadFile, _downloadFile, value.longitude)),
        address: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.address))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n58(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    pending_approval: null;
} | {
    rejected: null;
} | {
    suspended: null;
}): Status__1 {
    return "active" in value ? Status__1.active : "pending_approval" in value ? Status__1.pending_approval : "rejected" in value ? Status__1.rejected : "suspended" in value ? Status__1.suspended : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    pending: null;
} | {
    completed: null;
}): InquiryStatus {
    return "new" in value ? InquiryStatus.new : "pending" in value ? InquiryStatus.pending : "completed" in value ? InquiryStatus.completed : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    question: null;
} | {
    feedback: null;
} | {
    booking: null;
}): InquiryType {
    return "question" in value ? InquiryType.question : "feedback" in value ? InquiryType.feedback : "booking" in value ? InquiryType.booking : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    featured: null;
} | {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Status {
    return "featured" in value ? Status.featured : "pending" in value ? Status.pending : "approved" in value ? Status.approved : "rejected" in value ? Status.rejected : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Category>): Array<Category> {
    return value.map((x)=>from_candid_Category_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Inquiry>): Array<Inquiry> {
    return value.map((x)=>from_candid_Inquiry_n28(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkerProfile>): Promise<Array<WorkerProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_WorkerProfile_n35(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n56(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n74(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_InquiryStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryStatus): _InquiryStatus {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_InquiryType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryType): _InquiryType {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_Inquiry_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Inquiry): _Inquiry {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_Integrations_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Integrations): _Integrations {
    return to_candid_record_n65(_uploadFile, _downloadFile, value);
}
function to_candid_Location_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Location): _Location {
    return to_candid_record_n72(_uploadFile, _downloadFile, value);
}
function to_candid_Pricing_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Pricing): _Pricing {
    return to_candid_record_n67(_uploadFile, _downloadFile, value);
}
function to_candid_Schedule_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Schedule): _Schedule {
    return to_candid_record_n69(_uploadFile, _downloadFile, value);
}
function to_candid_Status__1_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status__1): _Status__1 {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
async function to_candid_WorkerProfile_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkerProfile): Promise<_WorkerProfile> {
    return await to_candid_record_n61(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Status__1;
    name: string;
    description?: string;
}): {
    id: string;
    status: _Status__1;
    name: string;
    description: [] | [string];
} {
    return {
        id: value.id,
        status: to_candid_Status__1_n13(_uploadFile, _downloadFile, value.status),
        name: value.name,
        description: value.description ? candid_some(value.description) : candid_none()
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: InquiryStatus;
    response_text?: string;
    created_at: bigint;
    worker_id: string;
    customer_contact?: string;
    response_given: boolean;
    customer_name?: string;
    inquiry_text: string;
    inquiry_type: InquiryType;
}): {
    id: string;
    status: _InquiryStatus;
    response_text: [] | [string];
    created_at: bigint;
    worker_id: string;
    customer_contact: [] | [string];
    response_given: boolean;
    customer_name: [] | [string];
    inquiry_text: string;
    inquiry_type: _InquiryType;
} {
    return {
        id: value.id,
        status: to_candid_InquiryStatus_n17(_uploadFile, _downloadFile, value.status),
        response_text: value.response_text ? candid_some(value.response_text) : candid_none(),
        created_at: value.created_at,
        worker_id: value.worker_id,
        customer_contact: value.customer_contact ? candid_some(value.customer_contact) : candid_none(),
        response_given: value.response_given,
        customer_name: value.customer_name ? candid_some(value.customer_name) : candid_none(),
        inquiry_text: value.inquiry_text,
        inquiry_type: to_candid_InquiryType_n19(_uploadFile, _downloadFile, value.inquiry_type)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Status;
    principal: Principal;
    integrations: Integrations;
    pricing: Pricing;
    availability: Schedule;
    years_experience: bigint;
    photo?: ExternalBlob;
    phone_number: string;
    location: Location;
    full_name: string;
    category_id: string;
}): Promise<{
    id: string;
    status: _Status;
    principal: Principal;
    integrations: _Integrations;
    pricing: _Pricing;
    availability: _Schedule;
    years_experience: bigint;
    photo: [] | [_ExternalBlob];
    phone_number: string;
    location: _Location;
    full_name: string;
    category_id: string;
}> {
    return {
        id: value.id,
        status: to_candid_Status_n62(_uploadFile, _downloadFile, value.status),
        principal: value.principal,
        integrations: to_candid_Integrations_n64(_uploadFile, _downloadFile, value.integrations),
        pricing: to_candid_Pricing_n66(_uploadFile, _downloadFile, value.pricing),
        availability: to_candid_Schedule_n68(_uploadFile, _downloadFile, value.availability),
        years_experience: value.years_experience,
        photo: value.photo ? candid_some(await to_candid_ExternalBlob_n70(_uploadFile, _downloadFile, value.photo)) : candid_none(),
        phone_number: value.phone_number,
        location: to_candid_Location_n71(_uploadFile, _downloadFile, value.location),
        full_name: value.full_name,
        category_id: value.category_id
    };
}
function to_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    website_url?: string;
    instagram_handle?: string;
    whatsapp_number?: string;
    facebook_username?: string;
}): {
    website_url: [] | [string];
    instagram_handle: [] | [string];
    whatsapp_number: [] | [string];
    facebook_username: [] | [string];
} {
    return {
        website_url: value.website_url ? candid_some(value.website_url) : candid_none(),
        instagram_handle: value.instagram_handle ? candid_some(value.instagram_handle) : candid_none(),
        whatsapp_number: value.whatsapp_number ? candid_some(value.whatsapp_number) : candid_none(),
        facebook_username: value.facebook_username ? candid_some(value.facebook_username) : candid_none()
    };
}
function to_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rate_per_day?: bigint;
    special_offers: Array<string>;
    rate_per_hour?: bigint;
    currency?: string;
}): {
    rate_per_day: [] | [bigint];
    special_offers: Array<string>;
    rate_per_hour: [] | [bigint];
    currency: [] | [string];
} {
    return {
        rate_per_day: value.rate_per_day ? candid_some(value.rate_per_day) : candid_none(),
        special_offers: value.special_offers,
        rate_per_hour: value.rate_per_hour ? candid_some(value.rate_per_hour) : candid_none(),
        currency: value.currency ? candid_some(value.currency) : candid_none()
    };
}
function to_candid_record_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    timezone?: string;
    close_time?: string;
    available_days: Array<string>;
    open_time?: string;
}): {
    timezone: [] | [string];
    close_time: [] | [string];
    available_days: Array<string>;
    open_time: [] | [string];
} {
    return {
        timezone: value.timezone ? candid_some(value.timezone) : candid_none(),
        close_time: value.close_time ? candid_some(value.close_time) : candid_none(),
        available_days: value.available_days,
        open_time: value.open_time ? candid_some(value.open_time) : candid_none()
    };
}
function to_candid_record_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude?: number;
    country?: string;
    city?: string;
    district?: string;
    longitude?: number;
    address?: string;
}): {
    latitude: [] | [number];
    country: [] | [string];
    city: [] | [string];
    district: [] | [string];
    longitude: [] | [number];
    address: [] | [string];
} {
    return {
        latitude: value.latitude ? candid_some(value.latitude) : candid_none(),
        country: value.country ? candid_some(value.country) : candid_none(),
        city: value.city ? candid_some(value.city) : candid_none(),
        district: value.district ? candid_some(value.district) : candid_none(),
        longitude: value.longitude ? candid_some(value.longitude) : candid_none(),
        address: value.address ? candid_some(value.address) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status__1): {
    active: null;
} | {
    pending_approval: null;
} | {
    rejected: null;
} | {
    suspended: null;
} {
    return value == Status__1.active ? {
        active: null
    } : value == Status__1.pending_approval ? {
        pending_approval: null
    } : value == Status__1.rejected ? {
        rejected: null
    } : value == Status__1.suspended ? {
        suspended: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryStatus): {
    new: null;
} | {
    pending: null;
} | {
    completed: null;
} {
    return value == InquiryStatus.new ? {
        new_: null
    } : value == InquiryStatus.pending ? {
        pending: null
    } : value == InquiryStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryType): {
    question: null;
} | {
    feedback: null;
} | {
    booking: null;
} {
    return value == InquiryType.question ? {
        question: null
    } : value == InquiryType.feedback ? {
        feedback: null
    } : value == InquiryType.booking ? {
        booking: null
    } : value;
}
function to_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    featured: null;
} | {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == Status.featured ? {
        featured: null
    } : value == Status.pending ? {
        pending: null
    } : value == Status.approved ? {
        approved: null
    } : value == Status.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
